=== secxndary/KYAR_Labs_2sem/XML1_2/XML_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://msiter.ru" xmlns="http://msiter.ru" elementFormDefault="qualified">

    <xs:element name="CONTAINER">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="INFO">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="SPECIALITY" maxOccurs="unbounded">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="UNIVERSITY" type="xs:string" />
                <xs:element name="GRADE" type="xs:string" />
                <xs:element name="NUMBER" type="xs:string" />
                <xs:element name="CITY" type="xs:string" />
            </xs:sequence>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    
</xs:schema>

=== secxndary/KYAR_Labs_2sem/XML1_2/XML1_with_schema.xml
<?xmlversion = "1.0" encoding = "UTF-8"?>
<?xml-stylesheet type = "text/css" href = "XMLstyle.css"?>

<CONTAINER xmlns="http://msiter.ru"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://msiter.ru XML_schema.xsd">

    <INFO>
        <SPECIALITY>
            <UNIVERSITY>ГрГУ</UNIVERSITY>
            <GRADE>308</GRADE>
            <NUMBER>75 человек</NUMBER>
            <CITY>Гродно</CITY>
        </SPECIALITY>

        <SPECIALITY>
            <UNIVERSITY>БГУ</UNIVERSITY>
            <GRADE>321</GRADE>
            <NUMBER>70 человек</NUMBER>
            <CITY>Минск</CITY>
        </SPECIALITY>

        <SPECIALITY>
            <UNIVERSITY>БГУИР</UNIVERSITY>
            <GRADE>335</GRADE>
            <NUMBER>65 человек</NUMBER>
            <CITY>Минск</CITY>
        </SPECIALITY>

        <SPECIALITY>
            <UNIVERSITY>БНТУ</UNIVERSITY>
            <GRADE>314</GRADE>
            <NUMBER>80 человек</NUMBER>
            <CITY>Минск</CITY>
        </SPECIALITY>

        <SPECIALITY>
            <UNIVERSITY>БрГУ</UNIVERSITY>
            <GRADE>315</GRADE>
            <NUMBER>75 человек</NUMBER>
            <CITY>Брест</CITY>
        </SPECIALITY>
    </INFO>
</CONTAINER>
